<a href="https://colab.research.google.com/github/ffigai/ETP-AgeAwareYTSafety/blob/main/etp_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install transformers datasets accelerate scikit-learn

In [ ]:
# !pip install google-api-python-client youtube-transcript-api

In [106]:
import pandas as pd
from google.colab import drive
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer
from datasets import Dataset
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
import torch
from sklearn.metrics import f1_score
from sklearn.metrics import fbeta_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
import numpy as np
import string
from googleapiclient.discovery import build
from youtube_transcript_api import YouTubeTranscriptApi
import re

In [3]:
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

DATA EXPLORATION

In [4]:
# Import datasets
harmful_df = pd.read_excel("/content/drive/MyDrive/etp/data/Harmful.xlsx")
harmless_df = pd.read_excel("/content/drive/MyDrive/etp/data/Harmless.xlsx")

In [5]:
# Combine
df = pd.concat([harmful_df, harmless_df], ignore_index=True)

In [ ]:
#df.head()

In [ ]:
#df.tail()

In [6]:
# Define target labels
"""
Addictive harms (ADD)
  - Online gameplay: Graphic game scenes, graphic game promotions
  - Drug/smoking/alcohol: promotion Tutorials on growing or distributing drug plants, depictions of smoking or alcohol use, glorification of drugs/smoking/alcohol
  - Gambling-play videos: Recorded gambling videos, casino gameplay, advertisements for casinos or gambling services

Hate and harassment harms (HH)
  - Insults and obscenities: Use of name-calling, insulting language, profanity targeted at individuals or groups
  - Identity attacks or misrepresentation: Misleading information or defamatory content about specific individuals
  - Hate speech based on gender, race, ethnicity, age, religion, political ideology, disability, or sexual orientation: Violence inciting or hatred towards targeted people

Physical harms (PH)
  - Self-injury and suicide: Videos alluding, advocating, or describing selfinjury or suicide
  - Eating disorder promotion: Promotion of eating disorders (e.g. pro-ana, promia, thinspiration)
  - Dangerous challenges and pranks: Depiction of dangerous behaviors that pose serious danger (e.g., tide pod challenge, blackout challenge)

Sexual harms (SXL)
  - Erotic scenes or images: Extracted clips from films, sexually explicit messages or images, description of the actual use of sex toys
  - Depictions of sexual acts and nudity: Pornography, masturbation, groping, upskirting, and depictions of sexual fetishes
  - Sexual abuse: Videos depicting sexual coercion, or exploitation, including non-consensual acts
"""

target_labels = ["ADD", "SXL", "PH", "HH"]

In [7]:
# Cleaning harm_cat column

# Replace NaN with empty string
df["harm_cat"] = df["harm_cat"].fillna("")

def encode_labels(row):
    categories = [c.strip() for c in row.split(",") if c.strip() != ""]

    # Remove IH and CB
    categories = [c for c in categories if c in target_labels]

    return categories

df["filtered_categories"] = df["harm_cat"].apply(encode_labels)

In [8]:
# Remove Rows That Only Had IH/CB

# Remove rows that had harmful label originally but after filtering have zero categories

df = df[
    (df["harm_cat"] == "") |
    (df["filtered_categories"].apply(len) > 0)
].copy()

In [9]:
# Multi-Hot encode
for label in target_labels:
    df.loc[:, label] = df["filtered_categories"].apply(
        lambda x: 1 if label in x else 0
    )

In [10]:
# Quick check
print(df[target_labels].head())
print("Total samples:", len(df))
print("Harmful rows:", (df[target_labels].sum(axis=1) > 0).sum())
print("Harmless rows:", (df[target_labels].sum(axis=1) == 0).sum())
for label in target_labels:
    print(label, df[label].sum())

    ADD  SXL  PH  HH
5     0    0   1   0
6     1    0   0   0
9     0    0   0   1
10    0    0   0   1
11    0    0   0   1
Total samples: 13835
Harmful rows: 10533
Harmless rows: 3302
ADD 3416
SXL 1884
PH 3437
HH 2783

In [11]:
# Transcript Length
max_length = 256

In [12]:
# Keep Fields Separate,
df["text"] = (
    df[["title", "description", "transcript"]]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

Split → Tokenize → Build Dataset → Train Model → Evaluate → Get Harm Scores

In [13]:
# Train / Validation Split

# Keep only columns needed for modeling
model_df = df[["text"] + target_labels].copy()

# Ensure correct types
model_df["text"] = model_df["text"].astype(str)

for label in target_labels:
    model_df[label] = model_df[label].astype(int)

# Split
train_df, val_df = train_test_split(
    model_df,
    test_size=0.2,
    random_state=42
)

print("Train size:", len(train_df))
print("Validation size:", len(val_df))

Train size: 11068
Validation size: 2767

In [14]:
# Create labels column in pandas
train_df["labels"] = train_df[target_labels].values.tolist()
val_df["labels"] = val_df[target_labels].values.tolist()

# Ensure float type
train_df["labels"] = train_df["labels"].apply(lambda x: [float(i) for i in x])
val_df["labels"] = val_df["labels"].apply(lambda x: [float(i) for i in x])

# Keep only required columns
train_model_df = train_df[["text", "labels"]].copy()
val_model_df = val_df[["text", "labels"]].copy()

In [15]:
# Convert to HuggingFace Dataset
train_dataset = Dataset.from_pandas(train_model_df, preserve_index=False)
val_dataset = Dataset.from_pandas(val_model_df, preserve_index=False)

In [16]:
# Tokenizer
model_name = "distilroberta-base"
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=256
    )

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Map:   0%|          | 0/11068 [00:00<?, ? examples/s]

Map:   0%|          | 0/2767 [00:00<?, ? examples/s]

In [17]:
train_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels"]
)

val_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels"]
)

In [18]:
# Load model

model = AutoModelForSequenceClassification.from_pretrained(
    "distilroberta-base",
    num_labels=4,
    problem_type="multi_label_classification"
)

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: distilroberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [19]:
# Training Arguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    load_best_model_at_end=True
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [20]:
# Define Metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probs = torch.sigmoid(torch.tensor(logits)).numpy()
    preds = (probs > 0.5).astype(int)

    macro_f1 = f1_score(labels, preds, average="macro")
    micro_f1 = f1_score(labels, preds, average="micro")

    return {
        "macro_f1": macro_f1,
        "micro_f1": micro_f1
    }

In [21]:
# Initialize trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [22]:
# Start training
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma'].

TrainOutput(global_step=2076, training_loss=0.2414715120098724, metrics={'train_runtime': 958.3263, 'train_samples_per_second': 34.648, 'train_steps_per_second': 2.166, 'total_flos': 2199302192553984.0, 'train_loss': 0.2414715120098724, 'epoch': 3.0})

Analysis Phase

In [23]:
# Per-Class Performance Analysis
outputs = trainer.predict(val_dataset)

logits = torch.tensor(outputs.predictions)
probs = torch.sigmoid(logits).numpy()
preds = (probs > 0.5).astype(int)

labels = outputs.label_ids

print(classification_report(
    labels,
    preds,
    target_names=["ADD", "SXL", "PH", "HH"]
))

              precision    recall  f1-score   support

         ADD       0.90      0.85      0.87       655
         SXL       0.73      0.71      0.72       372
          PH       0.73      0.66      0.70       697
          HH       0.77      0.75      0.76       587

   micro avg       0.79      0.74      0.77      2311
   macro avg       0.78      0.74      0.76      2311
weighted avg       0.79      0.74      0.77      2311
 samples avg       0.60      0.59      0.59      2311

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [24]:
# Probability Distribution Analysis
score_df = pd.DataFrame(
    probs,
    columns=["ADD", "SXL", "PH", "HH"]
)

score_df.describe()

               ADD          SXL           PH           HH
count  2767.000000  2767.000000  2767.000000  2767.000000
mean      0.227935     0.140365     0.239991     0.194539
std       0.383237     0.277371     0.316047     0.316534
min       0.002206     0.002303     0.005417     0.002862
25%       0.009479     0.008203     0.019445     0.008735
50%       0.015267     0.017866     0.041457     0.015167
75%       0.113427     0.057298     0.441058     0.218902
max       0.989354     0.950159     0.962412     0.964013

In [26]:
# ROC-AUC Per Class
for i, label in enumerate(["ADD", "SXL", "PH", "HH"]):
    auc = roc_auc_score(labels[:, i], probs[:, i])
    print(f"{label} ROC-AUC: {auc:.4f}")

ADD ROC-AUC: 0.9559
SXL ROC-AUC: 0.9401
PH ROC-AUC: 0.9119
HH ROC-AUC: 0.9412

In [27]:
# Class Imbalance Check
for i, label in enumerate(["ADD", "SXL", "PH", "HH"]):
    print(label, "positives:", labels[:, i].sum())

ADD positives: 655.0
SXL positives: 372.0
PH positives: 697.0
HH positives: 587.0

In [30]:
# False Positive / False Negative Inspection
idx = 0  # choose category: ADD=0, SXL=1, PH=2, HH=3

false_negatives = np.where((labels[:, idx] == 1) & (preds[:, idx] == 0))[0]
false_positives = np.where((labels[:, idx] == 0) & (preds[:, idx] == 1))[0]

print("False negatives:", len(false_negatives))
print("False positives:", len(false_positives))

val_df.iloc[false_negatives[:5]]["text"]

False negatives: 99
False positives: 61

13582    Gay as fuck moment in L4D2 we was playin with ...
12439    Perfect Height for Plants? 0 how tall do you l...
2994     SNEAKING OUT MERCH: https://www.xcodeh.com/sho...
10932    Impossible 🎯 Obrigado por assistir! 💖\nThanks ...
11401    Drive By Pwnage I attempt some speed pwnage or...
Name: text, dtype: object

Threshold Optimization

In [31]:
# Search Optimal Threshold Per Class
optimal_thresholds = {}

for i, label in enumerate(["ADD", "SXL", "PH", "HH"]):
    best_f1 = 0
    best_thresh = 0.5

    for thresh in np.arange(0.1, 0.9, 0.05):
        preds_temp = (probs[:, i] > thresh).astype(int)
        f1 = f1_score(labels[:, i], preds_temp)

        if f1 > best_f1:
            best_f1 = f1
            best_thresh = thresh

    optimal_thresholds[label] = best_thresh
    print(f"{label}: Best threshold = {best_thresh:.2f}, F1 = {best_f1:.4f}")

ADD: Best threshold = 0.25, F1 = 0.8766
SXL: Best threshold = 0.30, F1 = 0.7355
PH: Best threshold = 0.25, F1 = 0.7366
HH: Best threshold = 0.35, F1 = 0.7730

In [33]:
# Recall-Optimized Thresholds (Safer for Children)
optimal_thresholds = {}

for i, label in enumerate(["ADD", "SXL", "PH", "HH"]):
    best_f2 = 0
    best_thresh = 0.5

    for thresh in np.arange(0.1, 0.9, 0.05):
        preds_temp = (probs[:, i] > thresh).astype(int)
        f2 = fbeta_score(labels[:, i], preds_temp, beta=2)

        if f2 > best_f2:
            best_f2 = f2
            best_thresh = thresh

    optimal_thresholds[label] = best_thresh
    print(f"{label}: Best threshold = {best_thresh:.2f}, F2 = {best_f2:.4f}")

ADD: Best threshold = 0.15, F2 = 0.8791
SXL: Best threshold = 0.10, F2 = 0.7751
PH: Best threshold = 0.10, F2 = 0.8159
HH: Best threshold = 0.10, F2 = 0.8331

In [34]:
# Recompute classification report using new thresholds
new_preds = np.zeros_like(probs)

for i, label in enumerate(["ADD", "SXL", "PH", "HH"]):
    thresh = optimal_thresholds[label]
    new_preds[:, i] = (probs[:, i] > thresh).astype(int)

from sklearn.metrics import classification_report
print(classification_report(labels, new_preds, target_names=["ADD","SXL","PH","HH"]))

              precision    recall  f1-score   support

         ADD       0.86      0.88      0.87       655
         SXL       0.58      0.85      0.69       372
          PH       0.58      0.91      0.71       697
          HH       0.66      0.89      0.76       587

   micro avg       0.66      0.89      0.76      2311
   macro avg       0.67      0.88      0.76      2311
weighted avg       0.68      0.89      0.76      2311
 samples avg       0.66      0.69      0.67      2311

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Age Range Rule Based Policy

In [ ]:
"""
Age 0–4

Characteristics:
Cannot contextualize violence
Extremely vulnerable to sexual content
High imitation risk (dangerous challenges)
No critical thinking for hate content

Therefore:
SXL → highest weight
PH → very high weight
ADD → high (especially imitation behaviors)
HH → moderate-high

Age 5–8

Characteristics:
Some understanding of fiction vs reality
Still highly vulnerable to imitation
Sensitive to bullying/hate language

Likely:
PH still very important
SXL important
HH increasingly relevant
ADD moderate

Age 9–12

Characteristics:
More social awareness
Exposure to peer dynamics
Increased risk of hate speech normalization
More exposure to addictive patterns

Likely:
HH becomes more important
ADD increases importance
PH still relevant
SXL still sensitive but slightly lower than 0–4
"""

In [44]:
# Define Age-Specific Decision Thresholds
thresholds = {
    "0_4": {
        "ADD": {"warn": 0.15, "block": 0.95},
        "SXL": {"warn": 0.10, "block": 0.70},
        "PH":  {"warn": 0.10, "block": 0.80},
        "HH":  {"warn": 0.20, "block": 0.80},
    },
    "5_8": {
        "ADD": {"warn": 0.20, "block": 0.97},
        "SXL": {"warn": 0.15, "block": 0.80},
        "PH":  {"warn": 0.15, "block": 0.85},
        "HH":  {"warn": 0.20, "block": 0.85},
    },
    "9_12": {
        "ADD": {"warn": 0.25, "block": 0.98},
        "SXL": {"warn": 0.20, "block": 0.85},
        "PH":  {"warn": 0.20, "block": 0.90},
        "HH":  {"warn": 0.25, "block": 0.90},
    }
}

labels_order = ["ADD", "SXL", "PH", "HH"]


def rule_based_decision(probs_row, age_group):
    age_thresholds = thresholds[age_group]

    # Step 1: Hard block
    for i, label in enumerate(labels_order):
        if probs_row[i] >= age_thresholds[label]["block"]:
            return "Block"

    # Step 2: Warn
    for i, label in enumerate(labels_order):
        if probs_row[i] >= age_thresholds[label]["warn"]:
            return "Warn"

    return "Allow"


import pandas as pd

decision_df = pd.DataFrame()

for age_group in thresholds.keys():
    decision_df[age_group] = [
        rule_based_decision(probs[i], age_group)
        for i in range(len(probs))
    ]

decision_df.head()

     0_4    5_8   9_12
0   Warn   Warn   Warn
1   Warn   Warn   Warn
2   Warn   Warn   Warn
3   Warn   Warn   Warn
4  Block  Block  Block

In [45]:
# Evaluate how many videos are Blocked / Warned per age group.
for age_group in decision_df.columns:
    print("\nAge:", age_group)
    print(decision_df[age_group].value_counts())

Age: 0_4
0_4
Block    1341
Warn     1281
Allow     145
Name: count, dtype: int64

Age: 5_8
5_8
Warn     1579
Block     998
Allow     190
Name: count, dtype: int64

Age: 9_12
9_12
Warn     1823
Block     666
Allow     278
Name: count, dtype: int64

In [46]:
# Inspect Risk Distribution
risk_df.describe()

               0_4          5_8         9_12
count  2767.000000  2767.000000  2767.000000
mean      0.200271     0.202980     0.205086
std       0.091922     0.084528     0.089769
min       0.020889     0.022168     0.020960
25%       0.130530     0.148926     0.145547
50%       0.210595     0.211794     0.206273
75%       0.265479     0.255832     0.257568
max       0.468177     0.468183     0.471047

In [47]:
# Calibrated Block Thresholds
pd.DataFrame(probs, columns=["ADD","SXL","PH","HH"]).describe(percentiles=[0.75,0.9,0.95,0.99])

               ADD          SXL           PH           HH
count  2767.000000  2767.000000  2767.000000  2767.000000
mean      0.227935     0.140365     0.239991     0.194539
std       0.383237     0.277371     0.316047     0.316534
min       0.002206     0.002303     0.005417     0.002862
50%       0.015267     0.017866     0.041457     0.015167
75%       0.113427     0.057298     0.441058     0.218902
90%       0.970213     0.737721     0.828090     0.820897
95%       0.982724     0.906719     0.902519     0.890988
99%       0.985791     0.937715     0.944808     0.933855
max       0.989354     0.950159     0.962412     0.964013

In [48]:
# Check Are almost all blocked videos actually harmful?
blocked_indices = decision_df["0_4"] == "Block"
blocked_labels = labels[blocked_indices]

print("Blocked but actually harmless:",
      (blocked_labels.sum(axis=1) == 0).sum())

Blocked but actually harmless: 124

Evaluate Policy Layer

In [49]:
# Define Ground Truth Harmful

# Harmful if any category is 1
is_harmful = (labels.sum(axis=1) > 0).astype(int)

In [50]:
# Evaluate Policy Per Age Group
def evaluate_policy(age_group):
    decisions = decision_df[age_group].values

    blocked = (decisions == "Block").astype(int)
    allowed = (decisions == "Allow").astype(int)

    # True harmful
    harmful = is_harmful

    TP = np.sum((blocked == 1) & (harmful == 1))  # correctly blocked harmful
    FP = np.sum((blocked == 1) & (harmful == 0))  # blocked harmless
    FN = np.sum((blocked == 0) & (harmful == 1))  # harmful not blocked
    TN = np.sum((blocked == 0) & (harmful == 0))  # harmless not blocked

    block_precision = TP / (TP + FP)
    block_recall = TP / (TP + FN)
    false_block_rate = FP / (FP + TN)
    false_allow_rate = FN / (FN + TP)

    print(f"\nAge Group: {age_group}")
    print("Block Precision:", round(block_precision, 3))
    print("Block Recall:", round(block_recall, 3))
    print("False Block Rate:", round(false_block_rate, 3))
    print("False Allow Rate:", round(false_allow_rate, 3))

for age in ["0_4", "5_8", "9_12"]:
    evaluate_policy(age)

Age Group: 0_4
Block Precision: 0.908
Block Recall: 0.575
False Block Rate: 0.191
False Allow Rate: 0.425

Age Group: 5_8
Block Precision: 0.925
Block Recall: 0.436
False Block Rate: 0.115
False Allow Rate: 0.564

Age Group: 9_12
Block Precision: 0.935
Block Recall: 0.294
False Block Rate: 0.066
False Allow Rate: 0.706

In [51]:
# Evaluate Protective Recall
"""
We redefine:

Protected = Block OR Warn
Unprotected = Allow
"""
def evaluate_protection(age_group):
    decisions = decision_df[age_group].values
    harmful = is_harmful

    protected = ((decisions == "Block") | (decisions == "Warn")).astype(int)

    TP = np.sum((protected == 1) & (harmful == 1))
    FN = np.sum((protected == 0) & (harmful == 1))

    protection_recall = TP / (TP + FN)

    print(f"\nAge Group: {age_group}")
    print("Protection Recall (Block+Warn):", round(protection_recall, 3))

for age in ["0_4", "5_8", "9_12"]:
    evaluate_protection(age)

Age Group: 0_4
Protection Recall (Block+Warn): 0.978

Age Group: 5_8
Protection Recall (Block+Warn): 0.968

Age Group: 9_12
Protection Recall (Block+Warn): 0.946

Explainability

In [67]:
device = model.device

In [79]:
# Helper function
def clean_tokens(tokens):
    clean = []
    for tok in tokens:
        if tok.startswith("Ġ"):
            clean.append(tok[1:])
        elif tok.startswith("##"):
            if len(clean) > 0:
                clean[-1] = clean[-1] + tok[2:]
        else:
            clean.append(tok)
    return clean

In [80]:
# Improved Gradient-Based Token Attribution
def explain_text_tokens(text, category_index, top_k=5):
    model.eval()
    device = model.device

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    )

    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)

    embeddings = model.roberta.embeddings(input_ids)
    embeddings.retain_grad()

    outputs = model(inputs_embeds=embeddings, attention_mask=attention_mask)
    logits = outputs.logits
    probs = torch.sigmoid(logits)

    target_prob = probs[0, category_index]

    model.zero_grad()
    target_prob.backward()

    grads = embeddings.grad[0]
    token_importance = torch.norm(grads, dim=1)

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0].detach().cpu())
    tokens = clean_tokens(tokens)

    scored_tokens = list(zip(tokens, token_importance.detach().cpu().numpy()))

    scored_tokens = sorted(scored_tokens, key=lambda x: x[1], reverse=True)

    scored_tokens = [
        t for t in scored_tokens
        if (
            t[0] not in ["<s>", "</s>", "<pad>"]
            and t[0] not in string.punctuation
            and len(t[0]) > 2
        )
    ]


    return scored_tokens[:top_k]

In [81]:
# Policy-Level Trigger Extraction
def get_policy_decision(probs_row, age_group):
    age_thresholds = thresholds[age_group]

    for i, label in enumerate(labels_order):
        p = probs_row[i]
        block_t = age_thresholds[label]["block"]

        if p >= block_t:
            return {
                "decision": "Block",
                "category": label,
                "probability": float(p),
                "threshold": block_t
            }

    for i, label in enumerate(labels_order):
        p = probs_row[i]
        warn_t = age_thresholds[label]["warn"]

        if p >= warn_t:
            return {
                "decision": "Warn",
                "category": label,
                "probability": float(p),
                "threshold": warn_t
            }

    return {
        "decision": "Allow",
        "category": None,
        "probability": None,
        "threshold": None
    }

In [82]:
# category explanation dictionary
category_descriptions = {
    "ADD": "addictive or substance-related content",
    "SXL": "sexual or explicit material",
    "PH": "physical harm or self-injury references",
    "HH": "hate speech or harassment-related content"
}

In [83]:
# Age formatter
def format_age(age_group):
    return age_group.replace("_", "-")

In [92]:
# Human-Readable Explanation Generator
def generate_human_explanation(age_group, policy_info, top_tokens):
    decision = policy_info["decision"]

    age_group = format_age(age_group)
    if decision == "Allow":
        return (
            f"This content is considered appropriate for age group {age_group}. "
            "No significant harmful indicators were detected."
        )

    category = policy_info["category"]
    prob = policy_info["probability"]
    threshold = policy_info["threshold"]

    description = category_descriptions.get(category, "harmful content")
    token_words = [t[0] for t in top_tokens]

    if decision == "Block":
        return (
            f"This content was blocked for age group {age_group} because it "
            f"shows a high likelihood of {description}. "
            f"The predicted risk score ({prob:.2f}) exceeded the safety threshold ({threshold:.2f}). "
            f"Key terms influencing this decision include: {', '.join(token_words)}."
        )

    if decision == "Warn":
        return (
            f"This content triggered a warning for age group {age_group} "
            f"due to potential {description}. "
            f"The predicted risk score ({prob:.2f}) exceeded the caution threshold ({threshold:.2f}). "
            f"Detected terms contributing to this assessment include: {', '.join(token_words)}."
        )

In [93]:
# Unified Explainability Function
def explain_video(text, probs_row, age_group):

    policy_info = get_policy_decision(probs_row, age_group)

    if policy_info["category"] is not None:
        category_index = labels_order.index(policy_info["category"])
        top_tokens = explain_text_tokens(text, category_index)
    else:
        top_tokens = []

    explanation_text = generate_human_explanation(
        age_group,
        policy_info,
        top_tokens
    )

    return {
        "age_group": age_group,
        "decision": policy_info["decision"],
        "trigger_category": policy_info["category"],
        "probability": policy_info["probability"],
        "threshold": policy_info["threshold"],
        "top_tokens": top_tokens,
        "human_readable_explanation": explanation_text
    }

SAMPLE USAGE

In [ ]:
df.head()

In [71]:
print(len(val_df))
print(probs.shape)
print(labels_order)

2767
(2767, 4)
['ADD', 'SXL', 'PH', 'HH']

In [103]:
sample_index = 2051

sample_text = val_df.iloc[sample_index]["text"]
sample_probs = probs[sample_index]

explanation = explain_video(sample_text, sample_probs, "0_4")
print(explanation["human_readable_explanation"])
explanation = explain_video(sample_text, sample_probs, "5_8")
print(explanation["human_readable_explanation"])
explanation = explain_video(sample_text, sample_probs, "9_12")
print(explanation["human_readable_explanation"])

This content triggered a warning for age group 0-4 due to potential hate speech or harassment-related content. The predicted risk score (0.72) exceeded the caution threshold (0.20). Detected terms contributing to this assessment include: ilation, Comp, raction, reon, orts.
This content triggered a warning for age group 5-8 due to potential hate speech or harassment-related content. The predicted risk score (0.72) exceeded the caution threshold (0.20). Detected terms contributing to this assessment include: ilation, Comp, raction, reon, orts.
This content triggered a warning for age group 9-12 due to potential hate speech or harassment-related content. The predicted risk score (0.72) exceeded the caution threshold (0.25). Detected terms contributing to this assessment include: ilation, Comp, raction, reon, orts.

ACTUAL USAGE

In [115]:
# Youtube Metadata Extractor
API_KEY = "AIzaSyAkTgOZfhS7Ja_0RULMiFC7Lso6w6bQBvI"

youtube = build("youtube", "v3", developerKey=API_KEY)

def extract_video_id(url):
    pattern = r"(?:v=|\/)([0-9A-Za-z_-]{11}).*"
    match = re.search(pattern, url)
    return match.group(1) if match else None

def fetch_youtube_metadata(url):
    video_id = extract_video_id(url)

    request = youtube.videos().list(
        part="snippet",
        id=video_id
    )
    response = request.execute()

    if not response["items"]:
        return None

    snippet = response["items"][0]["snippet"]

    title = snippet.get("title", "")
    description = snippet.get("description", "")
    channel = snippet.get("channelTitle", "")
    published_at = snippet.get("publishedAt", "")

    # Try transcript
    transcript_text = ""
    try:
        transcript = YouTubeTranscriptApi.get_transcript(video_id)
        transcript_text = " ".join([t["text"] for t in transcript])
    except:
        transcript_text = ""

    return {
        "video_id": video_id,
        "title": title,
        "description": description,
        "channel": channel,
        "published_at": published_at,
        "transcript": transcript_text
    }

In [109]:
# Convert Metadata to Model Input
def build_model_input(metadata):
    return f"{metadata['title']} {metadata['description']} {metadata['transcript']}"

In [110]:
# Inference Function
def predict_video(text):
    model.eval()
    device = model.device

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    )

    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        probs = torch.sigmoid(logits).cpu().numpy()[0]

    return probs

In [111]:
# Full Pipeline Wrapper
def analyze_youtube_video(url, age_group="0_4"):

    metadata = fetch_youtube_metadata(url)

    if metadata is None:
        return {"error": "Video not found"}

    text = build_model_input(metadata)
    probs = predict_video(text)

    explanation = explain_video(text, probs, age_group)

    return {
        "metadata": metadata,
        "harm_probabilities": dict(zip(labels_order, probs)),
        "explanation": explanation
    }

In [128]:
# Sample Usage
sample_video_id = "8l7nFWLcv7M"

url = "https://www.youtube.com/watch?v=" + sample_video_id
result = analyze_youtube_video(url, age_group="0_4")
print(result["explanation"]["human_readable_explanation"])
result = analyze_youtube_video(url, age_group="5_8")
print(result["explanation"]["human_readable_explanation"])
result = analyze_youtube_video(url, age_group="9_12")
print(result["explanation"]["human_readable_explanation"])

This content triggered a warning for age group 0-4 due to potential sexual or explicit material. The predicted risk score (0.64) exceeded the caution threshold (0.10). Detected terms contributing to this assessment include: love, scam, Elsa, Frozen, Joker.
This content triggered a warning for age group 5-8 due to potential sexual or explicit material. The predicted risk score (0.64) exceeded the caution threshold (0.15). Detected terms contributing to this assessment include: love, scam, Elsa, Frozen, Joker.
This content triggered a warning for age group 9-12 due to potential sexual or explicit material. The predicted risk score (0.64) exceeded the caution threshold (0.20). Detected terms contributing to this assessment include: love, scam, Elsa, Frozen, Joker.